# Generated by Django 3.1.7 on 2021-04-01 14:09

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='ModelTestimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('profession', models.CharField(blank=True, max_length=50, verbose_name='Profissão')),
                ('testimony', models.CharField(max_length=200, verbose_name='Depoimento')),
                ('social_media_link', models.URLField(max_length=50, verbose_name='Link')),
                ('image', models.ImageField(blank=True, upload_to='home\\testimonials', validators=[home.models.validador_image_size], verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
    ]
