# Generated by Django 3.1.7 on 2021-03-19 13:35

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTestimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('testimony', models.CharField(max_length=200)),
                ('social_media_link', models.URLField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='home\\testimonials', validators=[home.models.validador_image_size])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
