# Generated by Django 3.1.7 on 2021-03-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltestimony',
            options={'verbose_name': 'Depoimento', 'verbose_name_plural': 'Depoimentos'},
        ),
    ]
