# Generated by Django 3.1.7 on 2021-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_modelfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNewsletterAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assinatura de Newsletter',
                'verbose_name_plural': 'Assinaturas de Newsletter',
                'db_table': 'newsletter_assign',
            },
        ),
    ]
