# Generated by Django 3.1.7 on 2021-10-22 20:22

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210729_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcontact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='modelcontact',
            name='subject',
        ),
        migrations.AddField(
            model_name='modelcontact',
            name='office',
            field=models.TextField(default='', max_length=50, verbose_name='Ocupação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltestimony',
            name='image',
            field=models.ImageField(blank=True, upload_to='home\\testimonials', validators=[home.models.validador_image_size], verbose_name='Imagem'),
        ),
    ]
