version: '3.8'

services:
    mymbahome:
        image: mymbahome:0.1
        restart: always
        container_name: mymbahome
        env_file:
            - ./environment/env.mymbahome.env
            - ./environment/env.databaseaccess.env
        environment:
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=8000
        expose:
            - "8000"
        build:
            context: .
            dockerfile: ./mymbahome/Dockerfile
        volumes:
            - static:/app/static_files
            - media:/app/media
            - ./mymbahome:/app
        depends_on:
            - mysql
        command: gunicorn --bind 0.0.0.0:8000 mymbahome.wsgi
        networks:
            - default
        links:
            - mysql

    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        env_file:
            - ./environment/env.mysql.env
            - ./environment/env.databaseaccess.env
        volumes:
            - .mysqldata:/var/lib/mysql
        networks:
            - default
        command: --default-authentication-plugin=mysql_native_password

    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - mymbahome
        volumes:
            - static:/app/static_files
            - media:/app/media
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - default

volumes:
    media:
    static:

networks:
    default:
        name: home
        driver: bridge

# Obs
# docker-compose up -d -> for run compose
# change 'env_file' services level config for production enrivonment files
