version: '3.8'

services:
    mymbahome:
        image: mymbahome:0.1
        restart: always
        container_name: mymbahome
        env_file:
            - ./environment/dev.mymbahome.env
            - ./environment/dev.databaseaccess.env
        # environment:
        #     - VIRTUAL_HOST=localhost
        #     - VIRTUAL_PORT=8000
        expose:
            - "8000"
        build:
            context: .
            dockerfile: ./mymbahome/Dockerfile
        volumes:
            - static:/app/static_files
            - media:/app/media
            - ./mymbahome:/app
        depends_on:
            - mysql
        command: gunicorn --bind 0.0.0.0:8000 mymbahome.wsgi
        networks:
            - default
        links:
            - mysql

    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        env_file:
            - ./environment/dev.mysql.env
            - ./environment/dev.databaseaccess.env
        volumes:
            - .mysqldata:/var/lib/mysql
        networks:
            - default
        command: --default-authentication-plugin=mysql_native_password

    nginx-proxy-manager:
        image: jc21/nginx-proxy-manager
        restart: always
        depends_on:
            - mymbahome
        ports:
            - 80:80
            - 81:81
            - 443:443
        environment:
            DB_MYSQL_HOST: "nginx-proxy-manager-db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "admin"
            DB_MYSQL_PASSWORD: "admin"
            DB_MYSQL_NAME: "admin"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - static:/app/static_files
            - media:/app/media
        links:
            - mymbahome
        networks:
            - default
  
    nginx-proxy-manager-db:
        image: jc21/mariadb-aria:latest
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_DATABASE: "admin"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "admin"
        volumes:
            - ./data/mysql:/var/lib/mysql

volumes:
    media:
    static:

networks:
    default:
        name: home
        driver: bridge

# Obs
# docker-compose up -d -> for run compose
# change 'env_file' services level config for production enrivonment files
