# Generated by Django 3.1.7 on 2021-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social_media_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contribuinte',
                'verbose_name_plural': 'Contribuintes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelImageActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', help_text="'x'px 'x'px", null=True, upload_to='activity', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='ModelLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('type', models.CharField(choices=[('Projeto', 'Projeto'), ('Ação', 'Ação')], help_text='Ação: atividade pontual ou recorrente\nProjeto: atividade constante', max_length=20, verbose_name='Tipo de atividade')),
                ('headline', models.TextField(help_text='250 caracteres', max_length=250, verbose_name='Resumo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('impacted_animals', models.IntegerField(blank=True, help_text='Número inteiro', null=True, verbose_name='Animais impactados')),
                ('contributors', models.ManyToManyField(blank=True, to='projects.ModelContributor', verbose_name='Contribuintes')),
                ('images', models.ManyToManyField(blank=True, to='projects.ModelImageActivity', verbose_name='Imagens')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'activity',
            },
        ),
    ]
