# Generated by Django 3.1.7 on 2021-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social_media_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contribuinte',
                'verbose_name_plural': 'Contribuintes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headline', models.CharField(help_text='Resumo do projeto', max_length=250)),
                ('description', models.TextField()),
                ('contributors', models.ManyToManyField(blank=True, null=True, to='projects.ModelContributor')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headline', models.CharField(help_text='Resumo do projeto', max_length=250)),
                ('description', models.TextField()),
                ('impacted_animals', models.IntegerField(blank=True, null=True)),
                ('contributors', models.ManyToManyField(blank=True, null=True, to='projects.ModelContributor')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['name'],
            },
        ),
    ]
