# Generated by Django 3.1.7 on 2021-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaction',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='projects.ModelContributor', verbose_name='Contribuintes'),
        ),
        migrations.AlterField(
            model_name='modelaction',
            name='description',
            field=models.TextField(verbose_name='Descricão'),
        ),
        migrations.AlterField(
            model_name='modelaction',
            name='headline',
            field=models.CharField(help_text='250 caracteres', max_length=250, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='modelaction',
            name='impacted_animals',
            field=models.IntegerField(blank=True, help_text='Número inteiro', null=True, verbose_name='Animais impactados'),
        ),
        migrations.AlterField(
            model_name='modelaction',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modelproject',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='projects.ModelContributor', verbose_name='Contribuintes'),
        ),
        migrations.AlterField(
            model_name='modelproject',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='modelproject',
            name='headline',
            field=models.TextField(help_text='250 caracteres', max_length=250, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='modelproject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
