# Generated by Django 3.1.7 on 2021-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210324_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproject',
            name='image',
            field=models.ImageField(default='templates\\home\\assets\\img\\no-file.jpg', upload_to='projects', verbose_name='Imagem'),
        ),
    ]
