# Generated by Django 3.1.7 on 2021-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210402_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltypeactivity',
            name='type',
            field=models.CharField(help_text='Ação: atividade pontual ou recorrente\nProjeto: atividade constante', max_length=20, verbose_name='Tipo de atividade'),
        ),
    ]
