# Generated by Django 3.1.7 on 2021-04-02 13:20

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210402_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelactivity',
            name='type',
            field=models.ForeignKey(default=projects.models.ModelTypeActivity.get_or_create_default, on_delete=models.SET(projects.models.ModelTypeActivity.get_or_create_default), to='projects.modeltypeactivity'),
        ),
    ]
