# Generated by Django 3.1.7 on 2021-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210402_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltypeactivity',
            name='type',
            field=models.CharField(choices=[('project', 'Projeto'), ('action', 'Ação'), ('deleted', 'Deletado')], help_text='Ação: atividade pontual ou recorrente\nProjeto: atividade constante', max_length=20, unique=True, verbose_name='Tipo de atividade'),
        ),
    ]
