# Generated by Django 3.1.7 on 2021-04-05 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_modelactivity_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelactivity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
